package prepackets

import "github.com/qcasey/gokbus"

// RequestToPacket maps a string to a slice of relevant packets
var RequestToPacket = map[string][]gokbus.Packet{
	"PressMode":                 PressMode,
	"PressNum1":                 PressNum1,
	"PressNum2":                 PressNum2,
	"PressNum3":                 PressNum3,
	"PressNum4":                 PressNum4,
	"PressNum5":                 PressNum5,
	"PressNum6":                 PressNum6,
	"PressAM":                   PressAM,
	"PressFM":                   PressFM,
	"PressNext":                 PressNext,
	"PressPrev":                 PressPrev,
	"PressStereoPower":          PressStereoPower,
	"PressRecirculatingAir":     PressRecirculatingAir,
	"OpenTrunk":                 []gokbus.Packet{OpenTrunk},
	"TurnOnClownNose":           []gokbus.Packet{TurnOnClownNose},
	"FlashLowBeams":             []gokbus.Packet{FlashLowBeams},
	"FlashLowBeamsAndHazards":   []gokbus.Packet{FlashLowBeamsAndHazards},
	"FlashHighBeams":            []gokbus.Packet{FlashHighBeams},
	"FlashHighBeamsAndHazards":  []gokbus.Packet{FlashHighBeamsAndHazards},
	"FlashHighBeamsAndLowBeams": []gokbus.Packet{FlashHighBeamsAndLowBeams},
	"FlashHazards":              []gokbus.Packet{FlashHazards},
	"TurnOffAllExteriorLights":  []gokbus.Packet{TurnOffAllExteriorLights},
	"ToggleInteriorLights":      []gokbus.Packet{ToggleInteriorLights},
	"ToggleDoorLocks":           []gokbus.Packet{ToggleDoorLocks},
	"LockDriverDoor":            []gokbus.Packet{LockDriverDoor},
	"LockPassengerDoor":         []gokbus.Packet{LockPassengerDoor},
	"RequestDoorStatus":         []gokbus.Packet{RequestDoorStatus},
	"RequestIgnitionStatus":     []gokbus.Packet{RequestIgnitionStatus},
	"RequestLightStatus":        []gokbus.Packet{RequestLightStatus},
	"RequestTimeStatus":         []gokbus.Packet{RequestTimeStatus},
	"RequestOdometer":           []gokbus.Packet{RequestOdometer},
	"RequestPDCStatus":          []gokbus.Packet{RequestPDCStatus},
	"RequestVehicleStatus":      []gokbus.Packet{RequestVehicleStatus},
	"RequestTemperatureStatus":  []gokbus.Packet{RequestTemperatureStatus},
	"PopWindowsUp":              PopWindowsUp,
	"PopWindowsDown":            PopWindowsDown,
}
